'''
This file is to regenerate quality of life files for this package
'''

import os
directories:list[str] = []
dirs= [os.path.join(os.path.dirname(__file__),'elements')]

while dirs:
    d = dirs.pop(0)
    directories.append(d)
    for name in os.listdir(d):
        fqn = os.path.join(d,name)
        if os.path.isdir(fqn):
            dirs.append(fqn)

print(*directories)

for dir in directories:
    with open(os.path.join(dir,'__init__.py'),'w') as file:
        lines = ['#This file has been generated by gui/__main__.py\n']
        exports:list[str] = []
        subdirs:list[str] = []
        for file_name in os.listdir(dir):
            fqn = os.path.join(dir,file_name)
            if file_name == '__init__.py': continue
            if file_name.endswith('.py') and os.path.isfile(fqn):
                exported_name = file_name.removesuffix('.py')
                exports.append(exported_name)
                lines.append(f'from .{exported_name} import {exported_name}\n')
            elif not file_name.startswith('__') and os.path.isdir(fqn):
                subdirs.append(file_name)
        lines = lines[:1] + [f'from . import {subdir}\n' for subdir in subdirs] +['\n'] + lines[1:]
        exports = subdirs + exports
        lines.append('\n\n')
        lines.append('__all__ = [\n  ')
        lines.append(repr(exports).replace(', ',',\n  ')[1:-1])
        lines.append('\n]\n')
        # lines.append('\',\n    \''.join(exports))
        # lines.append('\'\n]')
        file.writelines(lines)

        

